# Dockerfile.client

FROM golang:1.24-alpine

WORKDIR /app

# Copy go.mod and go.sum first to leverage caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project
COPY . .

# Build client/main.go
RUN go build -o client ./main.go

EXPOSE 9090

CMD ["./client"]
