services:
  flaky:
    build:
      context: ./flaky-server
      dockerfile: Dockerfile.flaky
    ports:
      - "8081:8081"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    networks:
      - app-network
    ports:
      - "9090:9090"
    depends_on:
      - flaky

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  app-network:
    driver: bridge