
services:
  flaky:
    build:
      context: .
      dockerfile: Dockerfile.flaky
    ports:
      - "8081:8081"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "9090:9090"
    depends_on:
      - flaky

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
